-- 创建包含所有遗漏字段的完整表 node_day_ops_wide_full
-- 基于原始表 node_day_ops_wide 添加遗漏字段: idcId, idcBandwidth, transProvRate, isVm, isCloudVm, scheduleISPs, settlePeriodType

CREATE TABLE IF NOT EXISTS test.node_day_ops_wide_full (
    customerId           bigint               NOT NULL COMMENT '客户 Id',
    day                 date                 NOT NULL COMMENT '日期，格式：2006-01-02',
    nodeId              varchar(64)         NOT NULL COMMENT '节点 Id',
    analyzePeak95       bigint              COMMENT '',
    baseInfo_channelId  bigint              COMMENT '',
    baseInfo_signatoryId bigint             COMMENT '',
    baseInfo_bandwidth  double              COMMENT '',
    buildBandwidth      double              COMMENT '原始建设带宽，单位：Mbps',
    city                varchar(256)        COMMENT '城市',
    cost_guaranteedRate double              COMMENT '',
    cost_priceItemId    varchar(64)         COMMENT '',
    cost_priceItemName  varchar(128)        COMMENT '',
    cost_priceType      varchar(32)         COMMENT '',
    cost_price          decimal(18,4)        COMMENT '',
    cost_priceAfterBonus decimal(18,4)       COMMENT '',
    cost_measure       double              COMMENT '',
    cost_original      decimal(18,4)        COMMENT '',
    cost_bonus          decimal(18,4)        COMMENT '',
    cost_slaDeduction  decimal(18,4)        COMMENT '',
    cost_tobaDeduction  decimal(18,4)       COMMENT '',
    cost_settlement     decimal(18,4)        COMMENT '',
    cost_adjustmentAmount decimal(18,4)      COMMENT '',
    cost_finalAmount    decimal(18,4)        COMMENT '',
    customerName        varchar(128)        COMMENT '业务名称',
    deliveryType        varchar(32)         COMMENT '资源类型',
    evening20To23Avg    bigint              COMMENT '',
    eveningAvg         bigint              COMMENT '',
    eveningPeak95       bigint              COMMENT '',
    isBanTransProv      boolean             COMMENT '是否禁止跨省调度',
    isp                varchar(32)         COMMENT '运营商',
    name                varchar(128)        COMMENT '节点名称',
    natType             varchar(32)         COMMENT '网络类型',
    nodeTags            json                 COMMENT '节点标签',
    nodeType            varchar(32)         COMMENT '节点类型',
    os                  varchar(32)         COMMENT '操作系统',
    peak95              bigint              COMMENT '日95带宽，单位：bps',
    peak95Ratio         int                 COMMENT '',
    peak95Time          datetime            COMMENT '日95时间',
    peakMaxRatio        int                 COMMENT '',
    priceNumber         varchar(32)         COMMENT '价格编号',
    profit_profitAmount  decimal(18,4)        COMMENT '',
    profit_profitRate   decimal(18,6)        COMMENT '',
    profit_estimatedProfitAmount decimal(18,4) COMMENT '',
    profit_estimatedProfitRate decimal(18,6) COMMENT '',
    -- 新增遗漏字段
    idcId               varchar(64)         COMMENT '机房 Id',
    idcBandwidth        double              COMMENT '机房建设带宽，单位：Mbps',
    transProvRate        double              COMMENT '跨省调度比例',
    isVm                boolean             COMMENT '是否为虚拟机',
    isCloudVm           boolean             COMMENT '是否为云主机',
    scheduleISPs        json                 COMMENT '实际业务调度的运营商',
    settlePeriodType    varchar(32)         COMMENT '结算周期类型',
    -- 原有后续字段
    province            varchar(32)         COMMENT '省份',
    purchaserName        varchar(64)         COMMENT '采购员',
    quantityEnd         decimal(18,4)        COMMENT '',
    quantityType        varchar(32)         COMMENT '',
    realISP             varchar(64)         COMMENT '真实运营商',
    resourceType        varchar(32)         COMMENT '客户侧资源类型',
    revenue_guaranteedRate double            COMMENT '',
    revenue_priceItemId  varchar(64)         COMMENT '',
    revenue_priceItemName varchar(128)        COMMENT '',
    revenue_price       decimal(18,4)        COMMENT '',
    revenue_measure     double              COMMENT '',
    revenue_coefficientMeasure double      COMMENT '',
    revenue_amount      decimal(18,4)        COMMENT '',
    revenue_finalAmount decimal(18,4)        COMMENT '',
    revenue_estimatedFinalAmount decimal(18,4) COMMENT '',
    signatoryName        varchar(128)        COMMENT '客户名称',
    snapshotTime         datetime            COMMENT '快照时间',
    stage               varchar(32)         COMMENT '业务状态',
    stairType           varchar(32)         COMMENT '阶梯类型',
    stairs              json                 COMMENT '阶梯',
    state               varchar(32)         COMMENT '在线状态',
    tcpNatType          varchar(32)         COMMENT 'TCP NAT 类型',
    udpNatType          varchar(32)         COMMENT 'UDP NAT 类型',
    unEveningAvg        bigint              COMMENT '',
    updatedTime         datetime            COMMENT '更新时间',
    vendorId            bigint               COMMENT '供应商 Id',
    vendorSuggestCustomers json               COMMENT '矿主期望业务',
    virtualCustomers     json                 COMMENT '虚拟业务',
    webPort             varchar(32)         COMMENT '业务端口',
    webPortResult        varchar(32)         COMMENT '业务端口结果'
) ENGINE=OLAP
DUPLICATE KEY(customerId, day, nodeId)
DISTRIBUTED BY HASH(customerId) BUCKETS 32
PROPERTIES (
    "replication_num" = "1"
);
